# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SRKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SRKit

  ## Keychain，一般用于获取唯一设备标识
  pod 'KeychainSwift', '~> 14.0.0' # Required
  
  ## Http
  pod 'Alamofire', '~> 4.8.2' # Required
  
  ## 图片请求
  pod 'SDWebImage', '~> 5.0.0' # Optional 将会被其他的第三方库所依赖
  
  ## 日志系统
  pod 'CocoaLumberjack/Swift', '~> 3.5.2' # Required
  
  ## 富文本
  pod 'DTCoreText', '~> 1.6.21' # Required
  
  ## 进度控件
  pod 'MBProgressHUD', '~> 1.1.0' # Required
  pod 'M13ProgressSuite', '~> 1.2.9' # Required
  
  ## 键盘管理
  pod 'IQKeyboardManagerSwift', '~> 6.2.1' # Required
  
  ## 约束布局
  pod 'Cartography', '~> 3.1.0' # Required
  
  ## Json解析与封装
  pod 'SwiftyJSON', '~> 4.3.0' # Required
  
  ## Json与数据模型
  pod 'ObjectMapper', '~> 3.4.2'
  
  ## 加密与解密
  pod 'CryptoSwift', :git => "https://github.com/krzyzanowskim/CryptoSwift", :branch => "master" # Optional
  
  ## Toast
  pod 'Toast', '~> 4.0.0' # Required
  #pod 'Toast-Swift', '~> 5.0.0' # Required
  
  ## 上下拉刷新数据的列表控件
  pod 'MJRefresh', '~> 3.1.16' # Required
  
  ## 在iOS下搭建web服务器
  pod 'GCDWebServer', '~> 3.5.2' # Optional
  
  ## 状态机
  pod 'TransitionKit', '~> 2.2.1' # Optional
  
  ## 定制弹出框
  pod 'SCLAlertView', '~> 0.8' # Required, added in project->"ThirdParty" 因SCLAlertView.appearance没有设置为public，已添加到项目工程中的ThirdParty
  pod 'Popover', '~> 1.2.2' # Optional
  
  ## 弹出框
  pod 'REMenu', '~> 1.10' # Optional
  
  ## 电话号码查询
  pod 'libPhoneNumber-iOS', '~> 0.9.13'
end

target 'SRKitExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SRKitExample

  ## Keychain，一般用于获取唯一设备标识
  pod 'KeychainSwift', '~> 14.0.0' # Required
  
  ## Http
  pod 'Alamofire', '~> 4.8.2' # Required
  
  ## 图片请求
  pod 'SDWebImage', '~> 5.0.0' # Optional 将会被其他的第三方库所依赖
  
  ## 日志系统
  pod 'CocoaLumberjack/Swift', '~> 3.5.2' # Required
  
  ## 富文本
  pod 'DTCoreText', '~> 1.6.21' # Required
  
  ## 进度控件
  pod 'MBProgressHUD', '~> 1.1.0' # Required
  pod 'M13ProgressSuite', '~> 1.2.9' # Required
  
  ## 键盘管理
  pod 'IQKeyboardManagerSwift', '~> 6.2.1' # Required
  
  ## 约束布局
  pod 'Cartography', '~> 3.1.0' # Required
  
  ## Json解析与封装
  pod 'SwiftyJSON', '~> 4.3.0' # Required
  
  ## Json与数据模型
  pod 'ObjectMapper', '~> 3.4.2'
  
  ## 加密与解密
  pod 'CryptoSwift', :git => "https://github.com/krzyzanowskim/CryptoSwift", :branch => "master" # Optional
  
  ## Toast
  pod 'Toast', '~> 4.0.0' # Required
  #pod 'Toast-Swift', '~> 5.0.0' # Required
  
  ## 上下拉刷新数据的列表控件
  pod 'MJRefresh', '~> 3.1.16' # Required
  
  ## 在iOS下搭建web服务器
  pod 'GCDWebServer', '~> 3.5.2' # Optional
  
  ## 状态机
  pod 'TransitionKit', '~> 2.2.1' # Optional
  
  ## 定制弹出框
  pod 'SCLAlertView', '~> 0.8' # Required, added in project->"ThirdParty" 因SCLAlertView.appearance没有设置为public，已添加到项目工程中的ThirdParty
  pod 'Popover', '~> 1.2.2' # Optional
  
  ## 弹出框
  pod 'REMenu', '~> 1.10' # Optional
  
  ## 电话号码查询
  pod 'libPhoneNumber-iOS', '~> 0.9.13'
end
